// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PantryClub.Services.Users.DbContexts;

#nullable disable

namespace PantryClub.Services.Users.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230606211422_InitialUser")]
    partial class InitialUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PantryClub.Services.Users.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("00ea5b3e-307c-421d-9a34-670a25d03829"),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anesu@gmail.com",
                            FirstName = "Anesu",
                            LastName = "Mutumwa"
                        },
                        new
                        {
                            UserId = new Guid("4a8321c1-c147-490c-ac3a-401a81df6c5b"),
                            DateOfBirth = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "angel@gmail.com",
                            FirstName = "Angel",
                            LastName = "Mutumwa"
                        },
                        new
                        {
                            UserId = new Guid("94097710-8742-4f61-bf80-3a93a66f7493"),
                            DateOfBirth = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tendai@gmail.com",
                            FirstName = "Tendai",
                            LastName = "Mutumwa"
                        },
                        new
                        {
                            UserId = new Guid("f5b4a916-13ee-4f91-8e64-482db5ec47e8"),
                            DateOfBirth = new DateTime(1960, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "arielle@gmail.com",
                            FirstName = "Arielle",
                            LastName = "Mutumwa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
