// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PantryClub.Services.Orders.DbContexts;

#nullable disable

namespace PantryClub.Services.Orders.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PantryClub.Services.Orders.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("99400f3f-0deb-4d9e-bf4f-401d1988bfb9"),
                            Price = 15m,
                            ProductName = "Apple",
                            Quantity = 9,
                            UserId = new Guid("99b6c24c-0f37-4474-86ed-7e0611a0be83")
                        },
                        new
                        {
                            OrderId = new Guid("f44235ab-935a-4f51-bfd5-8fea7ddd0f39"),
                            Price = 17m,
                            ProductName = "Orange",
                            Quantity = 4,
                            UserId = new Guid("a5f799fe-1850-43f9-ad96-41454309a3ad")
                        },
                        new
                        {
                            OrderId = new Guid("a5b95104-4e75-4e7e-a01b-1b78409dcab0"),
                            Price = 19m,
                            ProductName = "Grape",
                            Quantity = 6,
                            UserId = new Guid("9b7cf18a-320c-4a71-8337-54558e2c7253")
                        },
                        new
                        {
                            OrderId = new Guid("3b766af9-37f9-446f-bd7f-f1fe87bb3b8c"),
                            Price = 11m,
                            ProductName = "Avocado",
                            Quantity = 8,
                            UserId = new Guid("9f9868f0-ae85-4932-a735-ac8bd34ec9ac")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
